version: '3.9'
services:
    web:
        image: nginx:latest
        ports:
            - "4443:443"
        volumes:
            - ./certs:/etc/ssl/certs
            - ./volumes/nginx/config/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./volumes/nginx/config/self-signed.conf:/etc/nginx/conf.d/self-signed.conf
            - ./volumes/nginx/config/ssl-params.conf:/etc/nginx/conf.d/ssl-params.conf
            - ./volumes/sites:/var/www/
        links:
            - php
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
            args:
                buildno: 1
        volumes:
            - ./volumes/sites:/var/www/
        depends_on:
            - postgres
    postgres:
        image: postgres:14.3-alpine
        ports:
            - '15432:5432'
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: main
        volumes:
            - ./volumes/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./volumes/postgres/postgres-data:/var/lib/postgresql/data
            - ./volumes/postgres/postgres-backup:/var/lib/postgresql/backup